---
- name: Deploy Online Judge Application
  hosts: app_servers
  become: yes

  vars:
    dockerhub_username: "sivasomanath2502"
    image_tag: "{{ image_tag | default('latest') }}"
    app_dir: "/opt/online-judge"

  tasks:

    - name: Create application directory
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'

    - name: Copy docker-compose file
      copy:
        src: "../../docker-compose.prod.yml"
        dest: "{{ app_dir }}/docker-compose.prod.yml"
        mode: '0644'

    - name: Pull latest submission-service image
      community.docker.docker_image:
        name: "{{ dockerhub_username }}/submission-service"
        tag: "{{ image_tag }}"
        source: pull
        force_source: yes

    - name: Pull latest worker-service image
      community.docker.docker_image:
        name: "{{ dockerhub_username }}/worker-service"
        tag: "{{ image_tag }}"
        source: pull
        force_source: yes

    - name: Pull latest result-service image
      community.docker.docker_image:
        name: "{{ dockerhub_username }}/result-service"
        tag: "{{ image_tag }}"
        source: pull
        force_source: yes

    - name: Pull latest api-gateway image
      community.docker.docker_image:
        name: "{{ dockerhub_username }}/api-gateway"
        tag: "{{ image_tag }}"
        source: pull
        force_source: yes

    - name: Pull latest admin-service image
      community.docker.docker_image:
        name: "{{ dockerhub_username }}/admin-service"
        tag: "{{ image_tag }}"
        source: pull
        force_source: yes

    - name: Pull latest frontend image
      community.docker.docker_image:
        name: "{{ dockerhub_username }}/online-judge-frontend"
        tag: "{{ image_tag }}"
        source: pull
        force_source: yes

    - name: Deploy application
      environment:
        IMAGE_TAG: "{{ image_tag }}"
        DOCKERHUB_USERNAME: "{{ dockerhub_username }}"
      shell: |
        docker-compose -f docker-compose.prod.yml up -d --remove-orphans
      args:
        chdir: "{{ app_dir }}"

    - name: Wait for API Gateway port to be ready
      wait_for:
        host: localhost
        port: 8090
        delay: 20
        timeout: 180

    - name: Health check — API Gateway
      uri:
        url: http://localhost:8090/actuator/health
        status_code: 200
      register: health_check
      retries: 10
      delay: 15
      until: health_check.status == 200

    - name: Show health status
      debug:
        msg: "Application is UP — {{ health_check.json.status }}"