server.port=8082
spring.application.name=worker-service

spring.datasource.url=jdbc:mysql://localhost:3306/online_judge
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

rabbitmq.queue.job=job.queue
rabbitmq.queue.dlq=job.dlq
rabbitmq.exchange=job.exchange
rabbitmq.routing.key=job.routing.key

# Docker execution settings
execution.timeout.seconds=10
execution.memory.limit=128m
execution.cpu.limit=0.5

management.endpoints.web.exposure.include=health,info

# Manual ACK — worker controls when message is acknowledged
spring.rabbitmq.listener.simple.acknowledge-mode=manual
# Prevents channel from closing on queue declaration mismatch
spring.rabbitmq.listener.simple.missing-queues-fatal=false

result.service.url=http://localhost:8083