apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  namespace: wecode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
        - name: admin-service
          image: sivasomanath2502/admin-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
          envFrom:
            - configMapRef:
                name: wecode-config
            - secretRef:
                name: wecode-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"