apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-service
  namespace: wecode
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker-service
  template:
    metadata:
      labels:
        app: worker-service
    spec:
      containers:
        - name: worker-service
          image: sivasomanath2502/worker-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: wecode-config
            - secretRef:
                name: wecode-secret
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
            - name: judge-tmp
              mountPath: /judge-tmp
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
            type: Socket
        - name: judge-tmp
          hostPath:
            path: /tmp/judge
            type: DirectoryOrCreate