server.port=8090
spring.application.name=api-gateway

# ==============================
# ROUTES
# ==============================

# Submission Service
spring.cloud.gateway.routes[0].id=submission-service
spring.cloud.gateway.routes[0].uri=http://submission-service:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/submissions/**

# Result Service
spring.cloud.gateway.routes[1].id=result-service
spring.cloud.gateway.routes[1].uri=http://result-service:8083
spring.cloud.gateway.routes[1].predicates[0]=Path=/results/**

# Worker Service (optional - usually internal)
spring.cloud.gateway.routes[2].id=worker-service
spring.cloud.gateway.routes[2].uri=http://worker-service:8082
spring.cloud.gateway.routes[2].predicates[0]=Path=/worker/**

# Admin Service
spring.cloud.gateway.routes[3].id=admin-service
spring.cloud.gateway.routes[3].uri=http://admin-service:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/admin/**

# ==============================
# ACTUATOR
# ==============================

management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.health.show-details=always

# ==============================
# LOGGING
# ==============================

logging.level.org.springframework.cloud.gateway=INFO
logging.level.com.onlinejudge.api_gateway=DEBUG