server.port=8083
spring.application.name=result-service

spring.datasource.url=jdbc:mysql://localhost:3306/online_judge
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# SSE timeout — 5 minutes
sse.timeout.milliseconds=300000

management.endpoints.web.exposure.include=health,info