pipeline {
    agent any

    tools {
        maven 'Maven 3'
        jdk 'JDK 17'
    }

    environment {
        DOCKERHUB_USERNAME = 'sivasomanath2502'
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage('Check Docker') {
            steps {
                sh 'docker --version'
            }
        }

        stage('Checkout') {
            steps {
                echo 'Checking out source code...'
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('online_judge/online-judge-backend') {
                    sh 'mvn -B clean package -DskipTests'
                }
            }
        }

        stage('Unit Tests') {
            steps {
                echo 'Skipping tests (not implemented yet)'
            }
        }

        stage('Docker Build') {
            steps {
                dir('online_judge/online-judge-backend') {
                    sh """
                        docker build -t ${DOCKERHUB_USERNAME}/submission-service:${IMAGE_TAG} -t ${DOCKERHUB_USERNAME}/submission-service:latest ./submission-service
                        docker build -t ${DOCKERHUB_USERNAME}/worker-service:${IMAGE_TAG} -t ${DOCKERHUB_USERNAME}/worker-service:latest ./worker-service
                        docker build -t ${DOCKERHUB_USERNAME}/result-service:${IMAGE_TAG} -t ${DOCKERHUB_USERNAME}/result-service:latest ./result-service
                        docker build -t ${DOCKERHUB_USERNAME}/api-gateway:${IMAGE_TAG} -t ${DOCKERHUB_USERNAME}/api-gateway:latest ./api-gateway
                        docker build -t ${DOCKERHUB_USERNAME}/admin-service:${IMAGE_TAG} -t ${DOCKERHUB_USERNAME}/admin-service:latest ./admin-service
                    """
                }
            }
        }

        stage('Docker Push') {
            steps {
                timeout(time: 10, unit: 'MINUTES') {
                    withCredentials([usernamePassword(
                        credentialsId: 'docker-hub-credential',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )]) {
                        retry(3) {
                            sh """
                                echo "\$DOCKER_PASS" | docker login -u "\$DOCKER_USER" --password-stdin

                                docker push ${DOCKERHUB_USERNAME}/submission-service:${IMAGE_TAG}
                                docker push ${DOCKERHUB_USERNAME}/submission-service:latest

                                docker push ${DOCKERHUB_USERNAME}/worker-service:${IMAGE_TAG}
                                docker push ${DOCKERHUB_USERNAME}/worker-service:latest

                                docker push ${DOCKERHUB_USERNAME}/result-service:${IMAGE_TAG}
                                docker push ${DOCKERHUB_USERNAME}/result-service:latest

                                docker push ${DOCKERHUB_USERNAME}/api-gateway:${IMAGE_TAG}
                                docker push ${DOCKERHUB_USERNAME}/api-gateway:latest

                                docker push ${DOCKERHUB_USERNAME}/admin-service:${IMAGE_TAG}
                                docker push ${DOCKERHUB_USERNAME}/admin-service:latest

                                docker logout
                            """
                        }
                    }
                }
            }
        }

        stage('Ansible Deploy') {
            steps {
                dir('online_judge/online-judge-backend/ansible') {
                    sh """
                        ansible-playbook playbooks/deploy-app.yml \
                            -e "image_tag=${IMAGE_TAG}" \
                            -e "dockerhub_username=${DOCKERHUB_USERNAME}"
                    """
                }
            }
        }
    }
    post {
        success {
            echo '✅ Pipeline completed successfully!'
        }
        failure {
            echo '❌ Pipeline failed!'
        }
        always {
            echo 'Pipeline finished.'
        }
    }
}