spring.cloud.gateway.routes[0].id=submission-service
spring.cloud.gateway.routes[0].uri=http://submission-service:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/submissions/**

spring.cloud.gateway.routes[1].id=result-service
spring.cloud.gateway.routes[1].uri=http://result-service:8083
spring.cloud.gateway.routes[1].predicates[0]=Path=/results/**

spring.cloud.gateway.routes[2].id=worker-service
spring.cloud.gateway.routes[2].uri=http://worker-service:8082
spring.cloud.gateway.routes[2].predicates[0]=Path=/worker/**

spring.cloud.gateway.routes[3].id=admin-service
spring.cloud.gateway.routes[3].uri=http://admin-service:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/admin/**

spring.data.redis.host=redis