pipeline {
    agent any

    environment {
        DOCKERHUB_USERNAME = 'sivasomanath2502'
        SERVICE_NAME       = 'online-judge-frontend'
        IMAGE_TAG          = "${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps { checkout scm }
        }

        stage('Install Dependencies') {
            steps {
                dir('online-judge-frontend') {
                    sh 'npm ci'
                }
            }
        }

        stage('Build') {
            steps {
                dir('online-judge-frontend') {
                    sh 'npm run build'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('online-judge-frontend') {
                    sh """
                        docker build \
                        -t ${DOCKERHUB_USERNAME}/${SERVICE_NAME}:${IMAGE_TAG} \
                        -t ${DOCKERHUB_USERNAME}/${SERVICE_NAME}:latest .
                    """
                }
            }
        }

        stage('Docker Push') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'docker-hub-credential',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh """
                        echo "\$DOCKER_PASS" | docker login -u "\$DOCKER_USER" --password-stdin
                        docker push ${DOCKERHUB_USERNAME}/${SERVICE_NAME}:${IMAGE_TAG}
                        docker push ${DOCKERHUB_USERNAME}/${SERVICE_NAME}:latest
                        docker logout
                    """
                }
            }
        }
    }
}