apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: wecode
spec:
  selector:
    app: logstash
  ports:
    - name: tcp-input
      port: 5000
      targetPort: 5000
    - name: monitoring
      port: 9600
      targetPort: 9600
  type: ClusterIP