apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-service
  namespace: wecode
spec:
  replicas: 2
  selector:
    matchLabels:
      app: result-service
  template:
    metadata:
      labels:
        app: result-service
    spec:
      containers:
        - name: result-service
          image: sivasomanath2502/result-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: wecode-config
            - secretRef:
                name: wecode-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 6
            timeoutSeconds: 5

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 150
            periodSeconds: 20
            failureThreshold: 3
            timeoutSeconds: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "300m"